### ISSUE TITLE
給料未払い問題

### ISSUE THREAD

**Issue by osa9** [senbei-holdings/senbei-holdings.github.io#7]
せんべいHDから長らく給料を支払ってもらっていません

**Comment by seibe2** [comment]
本サイトとは関係がありません

**Comment by seibe2** [comment]
Closeお願いします

**Comment by highemerly** [comment]
バグの修正後にCloneされます。

**Comment by seibe2** [comment]
Closeお願いします。

**Comment by highemerly** [comment]
Closeしてほしいならばpull requestをください。

**Comment by osa9** [comment]
サイト内にCoinHiveを設置して給料にあてるのはいかがでしょうか

**Comment by highemerly** [comment]
CoinHiveは捕まるのでだめです。

**Comment by highemerly** [comment]
#12 によりベアが未定となったためReopenします。

**Comment by seibe2** [comment]
ベア自体は行われていることが示唆されているため実質課題は解決したと言えますのでCloseとします。
